### PR TITLE
Add templates for diagrams.net

### PR DESCRIPTION
**Pull request by mrueg**
# Currently supported

* All shapes and X-As-A-Service Interaction

# TODO

* Collaborate and Facilitate Interaction

# Usage

* Download the TeamToplogies.xml
* File -> Open Library from -> Device
* Select the TeamTopologies.xml

### CODE REVIEW

**Comment by matthewskelton** [comment]
Thanks, @mrueg - do you think it is worth using a nice multi-line formatted version of the JSON instead of the very long single line?

**Comment by mrueg** [comment]
@matthewskelton the file is generated from diagrams.net where I created those shapes

**Comment by matthewskelton** [comment]
These shapes are great - thanks, @mrueg ! I am going to push some changes that align the shapes better to the versions in the TT book, but your shapes make a great starting point.

**Comment by matthewskelton** [comment]
@mrueg see commit a4c9cb7 - the CS team octagon is "wider", the Enabling team is vertical, and the XaaS interaction "square". 

The Collaboration and Facilitation shapes are going to be fun to draw!

**Pull request merged**
